import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        title: "A Study of History",
        author: "Arnold J. Toynbee",
        description:
            "Arnold Toynbee's analysis of the rise and fall of civilizations has been acknowledged as one of the great achievements of twentieth-century scholarship. D.C. Somervell's abridgement of this monumental work is a great achievement in its own right.",
        price: 5000,
        categoryName: "history",
        rating: 2,
        discount: 20,
        image: "https://i.ibb.co/T2pDSf9/51m-Fg-RBo-Li-L-SY291-BO1-204-203-200-QL40-FMwebp.webp",
    },
    {
        _id: uuid(),
        title: "Plagues and Peoples",
        author: "William H. McNeill",
        description:
            "Plagues and Peoples was an immediate critical and popular success, offering a radically new interpretation of world history as seen through the extraordinary impact--political, demographic, ecological, and psychological--of disease on cultures. ",
        price: 1000,
        categoryName: "history",
        rating: 4,
        discount: 10,
        image: "https://i.ibb.co/pjwkKHL/61vdzs-XM-AL-SY344-BO1-204-203-200.jpg",
    },
    {
        _id: uuid(),
        title: "The Guns of August",
        author: "Barbara Tuchman",
        price: 6000,
        categoryName: "history",
        rating: 4,
        discount: 50,
        image: "https://i.ibb.co/y5dyjV7/51ckb9r-Xkj-L-SX301-BO1-204-203-200.jpg",
    },
    {
        _id: uuid(),
        title: "The Origin of Species",
        author: "Charles Darwin",
        price: 2000,
        categoryName: "science",
        rating: 1,
        discount: 40,
        image: "https://i.ibb.co/yRFgY79/71-Utl-N4-Qf-UL.jpg",
    },
    {
        _id: uuid(),
        title: "QED: The Strange Theory of Light and Matter",
        author: "Richard Feynman",
        price: 3000,
        categoryName: "science",
        rating: 4,
        discount: 10,
        image: "https://i.ibb.co/3Y4HjRh/5100-AFQRX7-L-SX302-BO1-204-203-200.jpg",
    },
    {
        _id: uuid(),
        title: "Ideas And Opinions",
        author: "Albert Einstein",
        price: 4000,
        categoryName: "science",
        rating: 3,
        discount: 20,
        image: "https://i.ibb.co/TmyDgjj/717s6s-N5b3-L.jpg",
    },
    {
        _id: uuid(),
        title: "Lives of a Cell",
        author: "Lewis Thomas",
        price: 1000,
        categoryName: "science",
        rating: 5,
        discount: 30,
        image: "https://i.ibb.co/p3ftZZd/A1-Je-Ml-DMVg-L.jpg",
    },
    {
        _id: uuid(),
        title: "The Structure of Scientific Revolutions",
        author: "Thomas Kuhn",
        price: 3000,
        categoryName: "science",
        rating: 3,
        discount: 10,
        image: "https://i.ibb.co/XLc9PRP/71q-NW-I214-L.jpg",
    },
    {
        _id: uuid(),
        title: "In Search of Lost Time",
        author: "Marcel Proust",
        price: 1000,
        categoryName: "fiction",
        rating: 3.5,
        discount: 40,
        image: "https://i.ibb.co/6nY58fC/ohbd3xqukj7do2f0o5txmhghfsva.jpg",
    },
    {
        _id: uuid(),
        title: "One Hundred Years of Solitude",
        author: "Gabriel Garcia Marquez",
        price: 3000,
        categoryName: "fiction",
        rating: 3.5,
        discount: 25,
        image: "https://i.ibb.co/y4jzzG4/kxk6iwn543doz8jqbs2sckh2fcot.jpg",
    },
    {
        _id: uuid(),
        title: "War and Peace",
        author: "Leo Tolstoy",
        price: 1500,
        categoryName: "fiction",
        rating: 3,
        discount: 40,
        image: "https://i.ibb.co/KF6Xdtw/swd3lfscp8lshlhuwfjng9s92o8q.jpg",
    },
    {
        _id: uuid(),
        title: "To the Lighthouse",
        author: "Virginia Woolf",
        price: 5000,
        categoryName: "fiction",
        rating: 4.5,
        discount: 35,
        image: "https://i.ibb.co/25NpB3T/xyex2scmaoaj9cvf3hr0i7xn8c7x.jpg",
    },
    {
        _id: uuid(),
        title: "The Odyssey",
        author: "Homer",
        price: 7000,
        categoryName: "fiction",
        rating: 3,
        discount: 25,
        image: "https://i.ibb.co/mvkCxhY/ihwv965787rm0zvkj6hg3f2taasw.jpg",
    },
    {
        _id: uuid(),
        title: "Eloquent JavaScript, Third Edition",
        author: "Marijn Haverbeke",
        price: 4000,
        categoryName: "technology",
        rating: 4,
        discount: 10,
        image: "https://i.ibb.co/Ykq1pyL/91as-IC1f-Rw-L.jpg",
    },
    {
        _id: uuid(),
        title: "Practical Modern JavaScript",
        author: "Nicolás Bevacqua",
        price: 500,
        categoryName: "technology",
        rating: 3,
        discount: 15,
        image: "https://i.ibb.co/KLqT7dP/813hbklw-WBL.jpg",
    },
    {
        _id: uuid(),
        title: "Understanding ECMAScript 6",
        author: "Nicholas C. Zakas",
        price: 2000,
        categoryName: "technology",
        rating: 5,
        discount: 50,
        image: "https://i.ibb.co/HYH5dk7/512-T-d-VK6-L-SX376-BO1-204-203-200.jpg",
    },
    {
        _id: uuid(),
        title: "Speaking JavaScript",
        author: "Axel Rauschmayer",
        price: 3000,
        categoryName: "technology",
        rating: 1,
        discount: 70,
        image: "https://i.ibb.co/swhf0XP/51-AOPRqo-YTL-SX342-SY445-QL70-ML2.jpg",
    },
    {
        _id: uuid(),
        title: "Learning JavaScript Design Patterns",
        author: "Addy Osmani",
        price: 10000,
        categoryName: "technology",
        rating: 2.5,
        discount: 40,
        image: "https://i.ibb.co/s9jHR8G/91-Wlv-END3r-L.jpg",
    },
    {
        _id: uuid(),
        title: "You Don't Know JS Yet",
        author: "Kyle Simpson",
        price: 8000,
        categoryName: "technology",
        rating: 3,
        discount: 20,
        image: "https://i.ibb.co/dDCMGdg/71m-Kv-D89o-EL.jpg",
    },
];
